### PR TITLE
fix proxy-agent vulnerability

### PR DESCRIPTION
**Pull request by Leonmisha**
High            Code Injection in pac-resolver                                
Package         pac-resolver                                                  
Dependency of   proxy-agent                                                   
Path            proxy-agent > pac-proxy-agent > pac-resolver                  
More info       https://github.com/advisories/GHSA-9j49-mfvp-vmhm

### CODE REVIEW

**Comment by calamarico** [comment]
This PR should be merged @aghadiry

**Comment by coyoteecd** [comment]
@aghadiry could you merge and publish this?

**Comment by calamarico** [comment]
tumbleweed-acegif-45
🤣

**Comment by coyoteecd** [comment]
kind reminder

**Comment by mdial89f** [comment]
@aghadiry por favor

**Comment by calamarico** [comment]
👏

**Pull request merged**
